[custom.all.calculi]
type = "local"
path = "."
ipkg = "calculi.ipkg"
test = "test/test.ipkg"

[custom.all.calculi-typechecker-test]
type = "local"
path = "test"
ipkg = "test.ipkg"

[custom.all.flap]
type   = "github"
url    = "https://github.com/yellowsquid/idris-flap"
commit = "latest:master"
ipkg   = "flap.ipkg"
