name: Build LaTeX document

on:
  workflow_dispatch:
  push:
    paths: doc/**.tex

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: doc/
          root_file: main.tex
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Doc PDF
          path: doc/main.pdf
